ignore:
  - "**/gameWorksheet.sc"
  - "**/GUI.scala"
  - "**/Main.scala"
  - "**/resources/"
  - "**/HexModule.scala"
  - "**/FileIO_uPickle.scala"

coverage:
  status:
    patch:
      default:
        target: 75%