ignore:
  - "src/main/scala/gameWorksheet.sc"
  - "src/main/scala/aview/gui/GUI.scala"
  - "src/main/scala/Main.scala"
  - "src/main/resources/"
  coverage:
  range: 40..75
  round: down
  precision: 2