ignore:
  - "src/main/scala/testgrid.worksheet.sc"
  - "src/main/scala/gui/GUI.scala"
  - "src/main/scala/Main.scala"
  - "src/main/resources/"
  coverage:
  range: 40..75
  round: down
  precision: 2